### ISSUE TITLE
[Feature] Modal 만들기

### ISSUE THREAD

**Issue by EliseCho13** [skkuding/skkuzzim#21]
### 📌 Type of feature

Component

### ✏️ Describe the feature

ref의 boolean값에 따라 modal이 뜨고, 그 빈 내용을 slot으로 주어 필요한 경우에 가져가서 내용을 채워 넣을 수 있게 한다.
모달 바깥을 누르면 모달이 사라져야 하고, 모달이 떠 있을 때의 배경은 어두워져야한다.

### 🎨 Feature Image

<img width="425" alt="image" src="https://user-images.githubusercontent.com/84661751/212071269-a10fb47e-40e2-4868-a7d5-6cf124b59bc0.png">

**Comment by dotoleeoak** [comment]
VueUse의 `OnClickOutside`를 활용하면 쉽게 구현할 수 있어요!
참고: https://vueuse.org/core/onclickoutside/
