### ISSUE TITLE
[Bug] eslint error

### ISSUE THREAD

**Issue by conakoo** [skkuding/skkuzzim#37]
## 문제 상황
frontend .eslintrc.cjs 와 repository .eslintrc.js 파일에서 typescript plugin을 동시에 쓰고 있어 eslint에서 인식하지 못하는 것 같습니다.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/62930375/212544961-575ac086-9e07-4942-ad39-e513cac19728.png">

## 해결 방안
음 잘 모르겠습니다 ...
- frontend/.eslint.cjs 파일에 `root:true`를 추가하면 되나요?
- extend option에서 @vue/eslint-config-typescript 를 지우면 임시로 해결은 되네요.

**Comment by dotoleeoak** [comment]
방법이 몇 가지 있는데, @vue/eslint-config-typescript를 frontend package에서 지우고 root package에 설치하는 게 제일 좋을 것 같아요! 비슷한 이유로 skkuding/next에서는 eslint 관련 의존성을 전부 root에서 관리하고 있어요.

**Comment by conakoo** [comment]
@dotoleeoak `@vue/eslint-config-typescript` 를 지우게 되면 해당 경고가 뜨는데 무시해도 되는 부분일까요?

<img width="908" alt="image" src="https://user-images.githubusercontent.com/62930375/212547455-6f8fc5b9-fa3c-4a21-96ab-e34ad22cd500.png">

**Comment by dotoleeoak** [comment]
@goo314 `@vue/eslint-config-typescript`를 지워서 그런 건 아닌 것 같고, 아마 eslintrc.js에 정의된 설정 때문에 그런 것 같네요.
에러 메시지대로면 이 설정 지워도 괜찮을 것 같습니다!

```
ignorePatterns: ['.eslintrc.js'],
```

**Comment by conakoo** [comment]
> @goo314 `@vue/eslint-config-typescript`를 지워서 그런 건 아닌 것 같고, 아마 eslintrc.js에 정의된 설정 때문에 그런 것 같네요. 에러 메시지대로면 이 설정 지워도 괜찮을 것 같습니다!
> 
> ```
> ignorePatterns: ['.eslintrc.js'],
> ```

와우 해결됐습니다! 감사합니다 ~ 😆
