### ISSUE TITLE
[Feature] 예약 상세 정보 가져오기

### ISSUE THREAD

**Issue by lshtar13** [skkuding/skkuzzim#40]
### 📌 Describe the feature

시작시간과 끝나는 시간을 클라이언트로부터 받아 그 시간대에 있는 예약 상세 내역을 반환한다.
<html>
<body>

  | type | description | example
-- | -- | -- | --
Date | 시작 시간 | 2023-01-23T12:30:00
Date | 마지막 시간 | 2023-01-23T13:00:00

</body>
</html>
<html>
<body>

  | type | description
-- | -- | --
number | 예약 아이디
string | 예약자 이름
string | 소속
Date | 시작시간
Date | 끝시간
string | 모임이름
string[] | 참가자 이름

</body>
</html>

### 📚 Describe related database schema

model Reservation 

|칼럼명|자료형|비고|
-- | -- | --
  id | Int | @id @default(autoincrement())
  creator  |  String
  club      | String
  startTime|  DateTime| @map("start_time")
  endTime  |  DateTime |@map("end_time")
  purpose    |String
  createTime| DateTime |@default(now()) @map("create_time")
  updateTime| DateTime| @updatedAt @map("update_time")

model Member 
|칼럼명|자료형|비고|
--|--|--
  id     |       Int    |     @id @default(autoincrement())
  reservation |  Reservation | @relation(fields: [reservationId], references: [id])
  reservationId | Int     |    @map("reservation_id")
  username    |  String

### 📄 Use-Case(기획)

사용자가 특정 시점을 골랐을 때, 해당 시점에 해당하는 개별적인 예약정보를 알려주기 위해 만들었습니다.

**Comment by SH9480P** [comment]
@JungangHighschool 대전중앙고님~~
이슈 제목에 module-name: 지워주세요
이슈 템플릿에 있는 module-name:은 모듈 이름을 적으라는 말입니다.

ex) [Feature] Reservation: implement detailed Reservation GET API
